apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("home/", views.home_view, name="home"),

    path("signup_account_selection/", views.signup_account_selection_view, name="signup_account_selection"),

    path("teacher_signup/", views.teacher_signup_view, name="teacher_signup"),
    path("student_signup/", views.student_signup_view, name="student_signup"),

    path("login/", views.login_view, name="login"),

    path("userpage/", views.userpage_view, name="userpage"),

    path("logout/", views.logout_view, name="logout"),

]

apps/attendances/urls.py
from django.urls import path
from . import views

app_name = 'attendances'

urlpatterns = [
    path('qr_reader/<int:course_id>/', views.qr_reader_view, name='qr_reader'),
    path('save_attendance/', views.save_attendance, name='save_attendance'),
    path('attendance_list/<int:course_id>/', views.attendance_list_view, name='attendance_list'),
    path('export/<int:course_id>/', views.export_attendance_to_excel, name='export_attendance_to_excel'),
]

apps/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path('select/', views.select_course, name='select'),
    path('create/', views.create_course, name='create'),
]

qratendancesystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('apps.courses.urls')), 
    path("accounts/", include("apps.accounts.urls")),
    path('students_qr/', include('apps.students_qr.urls')),
    path('attendances/', include('apps.attendances.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/courses/models.py
from django.db import models
from django.conf import settings

class Course(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    start_time = models.TimeField()
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='courses')
    def __str__(self):
        return self.name

apps/courses/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Course
        fields = ['name','start_date', 'start_time']

        labels = {
            'name': '授業名',
            'start_date': '開始日時',
            'start_time': '開始時間',
        }

apps/courses/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Course
from .forms import CourseForm
from datetime import datetime, timedelta

# 授業選択
@login_required
def select_course(request):
    # 今週の授業とそれ以外と終了済み授業を分ける
    today = datetime.today().date()
    next_week = today + timedelta(days=7)

    # ログイン中の教員
    teacher = request.user

    # 教員の授業のみ表示 * 授業の時間を確認
    this_week_courses = Course.objects.filter(
        teacher=teacher,
        start_date__range=[today, next_week]
    ).order_by('start_date', 'start_time')

    other_courses = Course.objects.filter(
        teacher=teacher,
        start_date__gt=next_week
    ).order_by('start_date', 'start_time')

    finished_courses = Course.objects.filter(
        teacher=teacher,
        start_date__lt=today
    ).order_by('start_date', 'start_time')

    context = {
        'today': today,
        'this_week_courses': this_week_courses,
        'other_courses': other_courses,
        'finished_courses': finished_courses,
    }
    
    return render(request, 'courses/select_course.html', context)

# 授業作成
@login_required
def create_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.teacher = request.user
            course.save()
            return redirect('courses:select')
    else:
        form = CourseForm()
    return render(request, 'courses/create_course.html', {'form': form})

apps/templates/courses/create_course.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>新規授業作成</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>新規授業作成</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_name">授業名 : </label>
            {{ form.name }}
            <br>
            <br>
            <label for="id_start_time">開始日時 : </label>
            {{ form.start_date }}
            <br>
            <br>
            <label for="id_start_time">開始時間 : </label>
            {{ form.start_time }}
            <br>
            <br>
            <button type="submit">作成</button>
            <br>
            <br>
            <button type="button" onclick="location.href=`{% url 'courses:select' %}`">
                戻る
            </button>
        </form>
    </body>
</html>

apps/templates/courses/select_course.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>授業選択</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>授業選択</h1>

        <p>本日の日付: {{ today }}</p>

        <h2>今週の授業</h2>
        <ul>
            {% for course in this_week_courses %}
                <li>
                    授業名 : {{ course.name }} 開始日時 : {{ course.start_date }} 開始時間 : {{ course.start_time }}
                    <br>
                    <button type="button" onclick="location.href=`{% url 'attendances:qr_reader' course_id=course.id %}`">
                        QRコードリーダー
                    </button>
                    <button type="button" onclick="location.href=`{% url 'attendances:attendance_list' course_id=course.id %}`">
                        出席リスト
                    </button>
                </li>
            {% empty %}
                <li>今週の授業はありません。</li>
            {% endfor %}
        </ul>

        <h2>その他の授業</h2>
        <ul>
            {% for course in other_courses %}
                <li>
                    授業名 : {{ course.name }} 開始日時 : {{ course.start_date }} 開始時間 : {{ course.start_time }}
                    <br>
                    <button type="button" onclick="location.href=`{% url 'attendances:qr_reader' course_id=course.id %}`">
                        QRコードリーダー
                    </button>
                    <button type="button" onclick="location.href=`{% url 'attendances:attendance_list' course_id=course.id %}`">
                        出席リスト
                    </button>
                </li>
            {% empty %}
                <li>その他の授業はありません。</li>
            {% endfor %}
        </ul>

        <h2>終了済みの授業</h2>
        <ul>
            {% for course in finished_courses %}
                <li>
                    授業名 : {{ course.name }} 開始日時 : {{ course.start_date }} 開始時間 : {{ course.start_time }}
                    <br>
                    <button type="button" onclick="location.href=`{% url 'attendances:qr_reader' course_id=course.id %}`">
                        QRコードリーダー
                    </button>
                    <button type="button" onclick="location.href=`{% url 'attendances:attendance_list' course_id=course.id %}`">
                        出席リスト
                    </button>
                </li>
            {% empty %}
                <li>終了済みの授業はありません。</li>
            {% endfor %}
        </ul>

        <button type="button" onclick="location.href=`{% url 'courses:create' %}`">
            新規授業作成
        </button>
        <br>
        <br>
        <button type="button" onclick="location.href=`{% url 'accounts:userpage' %}`">
            戻る
        </button>
    </body>
</html>