apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("home/", views.home_view, name="home"),

    path("signup_account_selection/", views.signup_account_selection_view, name="signup_account_selection"),

    path("teacher_signup/", views.teacher_signup_view, name="teacher_signup"),
    path("student_signup/", views.student_signup_view, name="student_signup"),

    path("login/", views.login_view, name="login"),

    path("userpage/", views.userpage_view, name="userpage"),

    path("logout/", views.logout_view, name="logout"),

]

apps/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path('select/', views.select_course, name='select'),
    path('create/', views.create_course, name='create'),
]

apps/students_qr/urls.py
from django.urls import path
from . import views

app_name = 'students_qr'

urlpatterns = [
    path('generate/', views.generate_qr, name='generate_qr'),
]

qratendancesystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('apps.courses.urls')), 
    path("accounts/", include("apps.accounts.urls")),
    path('students_qr/', include('apps.students_qr.urls')),
    path('attendances/', include('apps.attendances.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    ACCOUNT_TYPE_CHOICES = [
        ('teacher', '教師'),
        ('student', '生徒'),
    ]

    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPE_CHOICES, default='student')

apps/courses/models.py
from django.db import models
from django.conf import settings

class Course(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    start_time = models.TimeField()
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='courses')
    def __str__(self):
        return self.name

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
import re

class TeacherSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.account_type = 'teacher'
        if commit:
            user.save()
        return user

class StudentSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    # バリデーション
    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     pattern = r'^G\d{5}$'
    #     if not re.match(pattern, username):
    #         raise forms.ValidationError("学籍番号は G***** の形式で入力してください。")
    #     return username
    
    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     if not email.endswith('@***.ac.jp'):
    #         raise forms.ValidationError("メールアドレスは @***.ac.jp の形式で入力してください。")
    #     return email
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.account_type = 'student'
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    def non_field_errors(self):
        errors = super().non_field_errors()
        return errors

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import LoginForm, TeacherSignUpForm, StudentSignUpForm
from django.contrib.auth.decorators import login_required

# ホーム
def home_view(request):
    return render(request, "accounts/home.html")

# サインイン
def signup_account_selection_view(request):
    if request.method == "POST":
        account_type = request.POST.get('account_type')
        if account_type in ['student']:
            request.session['account_type'] = account_type
            return redirect('accounts:student_signup')
        elif account_type in ['teacher']:
            request.session['account_type'] = account_type
            return redirect('accounts:teacher_signup')
    return render(request, "accounts/account_selection.html")

#教師用サインアップ
def teacher_signup_view(request):
    if request.method == "POST":
        form = TeacherSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:home")
    else:
        form = TeacherSignUpForm()
    param = {"form": form}
    return render(request, "accounts/teacher_signup.html", param)

#生徒用サインアップ
def student_signup_view(request):
    if request.method == "POST":
        form = StudentSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:home")
    else:
        form = StudentSignUpForm()
    param = {"form": form}
    return render(request, "accounts/student_signup.html", param)

# ログイン
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                login(request, user)
                return redirect("accounts:userpage")
    else:
        form = LoginForm()
    param = {"form": form}
    return render(request, "accounts/login.html", param)

# ログアウト
@login_required
def logout_view(request):
    logout(request)
    return render(request, "accounts/logout.html")

# ユーザーページ
@login_required
def userpage_view(request):
    return render(request, "accounts/userpage.html")

apps/templates/accounts/account_selection.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>アカウント選択</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>アカウントの種類を選択してください。</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" name="account_type" value="teacher">教師</button>
            <button type="submit" name="account_type" value="student">生徒</button>
        </form>
        <br>
        <button type="button" onclick="location.href=`{% url 'accounts:home' %}`">
            戻る
        </button>
    </body>
</html>

apps/templates/accounts/home.html
<!DOCTYPE html>
<html lang='ja'>
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ホーム</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>ホーム</h1>
        <button type="button" onclick="location.href=`{% url 'accounts:signup_account_selection' %}`">
            アカウント登録
        </button>
        <br>
        <br>
        <button type="button" onclick="location.href=`{% url 'accounts:login' %}`">
            ログイン
        </button>
    </body>
</html>

apps/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ログイン</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>ログイン</h1>
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %} 
            <label for="id_username">ユーザーネーム or 学籍番号</label>
            <br>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <br>
            <br>
            <label for="id_password">パスワード</label>
            <br>
            {{ form.password }}
            {% if form.non_field_errors %}
                <div class="error">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <br>
            <br>
            <button type="button" onclick="location.href=`{% url 'accounts:home' %}`">
                戻る
            </button>
            <input type="submit" value="ログイン" />
        </form>
    </body>
</html>

apps/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ログアウト</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>ログアウト</h1>
        <p>ログアウトしました。</p>
        <button type="button" onclick="location.href=`{% url 'accounts:home' %}`">
            ホームへ
        </button>
    </body>
</html>

apps/templates/accounts/student_signup.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>生徒アカウント登録</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>生徒アカウント登録</h1>
        <form action="{% url 'accounts:student_signup' %}" method="post">
            {% csrf_token %}
            <label for="id_username">学籍番号</label>
            <br>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <br>
            <br>
            <label for="id_email">メールアドレス</label>
            <br>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="error">
                    {% for error in form.email.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <br>
            <br>
            <label for="id_password1">パスワード</label>
            <br>
            {{ form.password1 }}
            <br>
            <br>
            <label for="id_password2">パスワード(確認用)</label>
            <br>
            {{ form.password2 }}
            <ul>
                <li>学籍番号、メールアドレスと似ているパスワード、<br>
                <li>よく使われるパスワードや数字のみのパスワードは使えません</li>
                <li>パスワードは最低8文字以上必要です</li>
            </ul>
            <br>
            <br>
            <button type="button" onclick="location.href=`{% url 'accounts:home' %}`">
                戻る
            </button>
            <input type="submit" value="登録" />
        </form>
    </body>
</html>

apps/templates/accounts/teacher_signup.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>教師アカウント登録</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>教師アカウント登録</h1>
        <form action="{% url 'accounts:teacher_signup' %}" method="post">
            {% csrf_token %}
            <label for="id_username">ユーザーネーム(教師名として表示されます)</label>
            <br>
            {{ form.username }}
            <br>
            <br>
            <label for="id_email">メールアドレス</label>
            <br>
            {{ form.email }}
            <br>
            <br>
            <label for="id_password1">パスワード</label>
            <br>
            {{ form.password1 }}
            <br>
            <br>
            <label for="id_password2">パスワード(確認用)</label>
            <br>
            {{ form.password2 }}
            <ul>
                <li>ユーザーネーム、メールアドレスと似ているパスワード、<br>
                <li>よく使われるパスワードや数字のみのパスワードは使えません</li>
                <li>パスワードは最低8文字以上必要です</li>
            </ul>
            <br>
            <br>
            <button type="button" onclick="location.href=`{% url 'accounts:home' %}`">
                戻る
            </button>
            <input type="submit" value="登録" />
        </form>
    </body>
</html>

apps/templates/accounts/userpage.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {% load static %}
        <meta charset='UTF-8' />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ユーザーページ</title>
    </head>
    <body>
        <header>
            <h1>QRAttendanceSystem</h1>
        </header>
        <h1>ユーザーページ</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_name">{{ user.username }} でログイン中</label>
            <br>
            <br>
            {% if user.account_type == 'teacher' %}
                <button type="button" onclick="location.href=`{% url 'courses:select' %}`">
                    授業管理ページへ
                </button>
            {% elif user.account_type == 'student' %}
                <button type="button" onclick="location.href=`{% url 'students_qr:generate_qr' %}`">
                    QRコードページへ
                </button>
            {% endif %}
            <br>
            <br>
            <button type="submit" formaction="{% url 'accounts:logout' %}">
                ログアウト
            </button>
        </form>
    </body>
</html>